In [1]:
import pandas as pd
import numpy as  np

In [2]:
df = pd.read_csv('../data/Preprocess_data_OutlierClip.csv')
df.head()

,specialty,appointment_time,gender,no_show,disability,place,appointment_shift,age,under_12_years_old,over_60_years_old,...,storm_day_before,rain_intensity,heat_intensity,appointment_date_continuous,Hipertension,Diabetes,Alcoholism,Handcap,Scholarship,SMS_received
0,psychotherapy,1970-01-01 00:00:00.000000017,F,yes,intellectual,Lake Marvinville,afternoon,9.0,1,0,...,1,no_rain,warm,01-01-2020,0,0,0,0,0,0
1,psychotherapy,1970-01-01 00:00:00.000000007,M,no,intellectual,ITAPEMA,morning,11.0,1,0,...,1,no_rain,cold,01-01-2020,0,0,0,0,0,0
2,speech therapy,1970-01-01 00:00:00.000000016,M,no,intellectual,ITAJAÍ,afternoon,8.0,1,0,...,1,no_rain,warm,01-01-2020,0,0,0,0,0,0
3,speech therapy,1970-01-01 00:00:00.000000014,M,yes,intellectual,Sarahside,afternoon,9.0,1,0,...,1,moderate,mild,01-01-2020,0,0,0,0,0,1
4,physiotherapy,1970-01-01 00:00:00.000000008,M,no,motor,ITAJAÍ,morning,12.0,0,0,...,1,no_rain,mild,01-01-2020,0,0,0,0,0,0

In [3]:
df.loc[3527]

specialty                                      physiotherapy
appointment_time               1970-01-01 00:00:00.000000008
gender                                                     M
no_show                                                  yes
disability                                      intellectual
place                                           Andersontown
appointment_shift                                    morning
age                                                      7.0
under_12_years_old                                         1
over_60_years_old                                          0
patient_needs_companion                                    1
average_temp_day                                       20.42
average_rain_day                                        0.15
max_temp_day                                            24.2
max_rain_day                                             2.1
rainy_day_before                                           0
storm_day_before                                           0
rain_intensity                                       no_rain
heat_intensity                                    heavy_cold
appointment_date_continuous                       08-02-2020
Hipertension                                               0
Diabetes                                                   0
Alcoholism                                                 0
Handcap                                                    0
Scholarship                                                0
SMS_received                                               0
Name: 3527, dtype: object

In [4]:
df.loc[43832]

specialty                                           pedagogo
appointment_time               1970-01-01 00:00:00.000000013
gender                                                     M
no_show                                                   no
disability                                      intellectual
place                                            B. CAMBORIU
appointment_shift                                  afternoon
age                                                     10.0
under_12_years_old                                         1
over_60_years_old                                          0
patient_needs_companion                                    1
average_temp_day                                       11.61
average_rain_day                                         0.0
max_temp_day                                            16.4
max_rain_day                                             0.0
rainy_day_before                                           1
storm_day_before                                           1
rain_intensity                                       no_rain
heat_intensity                                          cold
appointment_date_continuous                       20-06-2020
Hipertension                                               0
Diabetes                                                   0
Alcoholism                                                 0
Handcap                                                    0
Scholarship                                                0
SMS_received                                               0
Name: 43832, dtype: object

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109304 entries, 0 to 109303
Data columns (total 26 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   specialty                    109304 non-null  object
 1   appointment_time             109304 non-null  object
 2   gender                       109304 non-null  object
 3   no_show                      109304 non-null  object
 4   disability                   109304 non-null  object
 5   place                        109304 non-null  object
 6   appointment_shift            109304 non-null  object
 7   age                          109304 non-null  float64
 8   under_12_years_old           109304 non-null  int64
 9   over_60_years_old            109304 non-null  int64
 10  patient_needs_companion      109304 non-null  int64
 11  average_temp_day             109304 non-null  float64
 12  average_rain_day             109304 non-null  float64
 13  max_temp_day                 109304 non-null  float64
 14  max_rain_day                 109304 non-null  float64
 15  rainy_day_before             109304 non-null  int64
 16  storm_day_before             109304 non-null  int64
 17  rain_intensity               109304 non-null  object
 18  heat_intensity               109304 non-null  object
 19  appointment_date_continuous  109304 non-null  object
 20  Hipertension                 109304 non-null  int64
 21  Diabetes                     109304 non-null  int64
 22  Alcoholism                   109304 non-null  int64
 23  Handcap                      109304 non-null  int64
 24  Scholarship                  109304 non-null  int64
 25  SMS_received                 109304 non-null  int64
dtypes: float64(5), int64(11), object(10)
memory usage: 21.7+ MB

In [4]:
df.isnull().sum()

specialty                      0
appointment_time               0
gender                         0
no_show                        0
disability                     0
place                          0
appointment_shift              0
age                            0
under_12_years_old             0
over_60_years_old              0
patient_needs_companion        0
average_temp_day               0
average_rain_day               0
max_temp_day                   0
max_rain_day                   0
rainy_day_before               0
storm_day_before               0
rain_intensity                 0
heat_intensity                 0
appointment_date_continuous    0
Hipertension                   0
Diabetes                       0
Alcoholism                     0
Handcap                        0
Scholarship                    0
SMS_received                   0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df['no_show'].value_counts()

no_show
no     74516
yes    34788
Name: count, dtype: int64

In [7]:
#Copy_safty
df_fe = df.copy()

In [8]:
#STEP 1: TARGET ENCODING (NO-SHOW)

df_fe['no_show']=df_fe['no_show'].map({'no':0,'yes':1})
df_fe

,specialty,appointment_time,gender,no_show,disability,place,appointment_shift,age,under_12_years_old,over_60_years_old,...,storm_day_before,rain_intensity,heat_intensity,appointment_date_continuous,Hipertension,Diabetes,Alcoholism,Handcap,Scholarship,SMS_received
0,psychotherapy,1970-01-01 00:00:00.000000017,F,1,intellectual,Lake Marvinville,afternoon,9.0,1,0,...,1,no_rain,warm,01-01-2020,0,0,0,0,0,0
1,psychotherapy,1970-01-01 00:00:00.000000007,M,0,intellectual,ITAPEMA,morning,11.0,1,0,...,1,no_rain,cold,01-01-2020,0,0,0,0,0,0
2,speech therapy,1970-01-01 00:00:00.000000016,M,0,intellectual,ITAJAÍ,afternoon,8.0,1,0,...,1,no_rain,warm,01-01-2020,0,0,0,0,0,0
3,speech therapy,1970-01-01 00:00:00.000000014,M,1,intellectual,Sarahside,afternoon,9.0,1,0,...,1,moderate,mild,01-01-2020,0,0,0,0,0,1
4,physiotherapy,1970-01-01 00:00:00.000000008,M,0,motor,ITAJAÍ,morning,12.0,0,0,...,1,no_rain,mild,01-01-2020,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109299,psychotherapy,1970-01-01 00:00:00.000000016,M,1,intellectual,ITAJAÍ,afternoon,18.0,0,0,...,1,no_rain,mild,11-05-2021,0,0,0,0,0,0
109300,speech therapy,1970-01-01 00:00:00.000000009,F,1,motor,Port Georgestad,morning,18.0,0,0,...,1,moderate,warm,11-05-2021,0,0,0,0,0,0
109301,psychotherapy,1970-01-01 00:00:00.000000013,F,0,intellectual,Erinton,afternoon,8.0,1,0,...,1,moderate,mild,11-05-2021,0,0,0,0,0,1
109302,physiotherapy,1970-01-01 00:00:00.000000008,F,0,motor,CAMBORIU,morning,7.0,1,0,...,1,no_rain,warm,11-05-2021,0,0,0,0,0,0
109303,psychotherapy,1970-01-01 00:00:00.000000011,M,0,none,ITAJAÍ,morning,12.0,0,0,...,1,weak,cold,12-05-2021,0,0,0,0,0,0

In [9]:

df['no_show'].unique()

array(['yes', 'no'], dtype=object)

In [10]:
df['no_show'] = df['no_show'].astype(str).str.strip().str.lower()

df['no_show'] = df['no_show'].map({'no': 0, 'yes': 1})

In [11]:
df['no_show'].value_counts(dropna=False)

no_show
0    74516
1    34788
Name: count, dtype: int64

In [12]:
#STEP 2: DATE FEATURES (CORE FEATURE)
df_fe['appointment_time'] = pd.to_datetime(df_fe['appointment_time'], errors='coerce')
df_fe['appointment_date_continuous'] = pd.to_datetime(df_fe['appointment_date_continuous'], errors='coerce')

df_fe['hour'] = df_fe['appointment_time'].dt.hour
df_fe['day'] = df_fe['appointment_time'].dt.day
df_fe['month'] = df_fe['appointment_time'].dt.month
df_fe['weekday'] = df_fe['appointment_time'].dt.dayofweek
df_fe['week'] = df_fe['appointment_date_continuous'].dt.isocalendar().week

In [13]:
#STEP 3: AGE FEATURES
df_fe['age_group'] = pd.cut(
    df_fe['age'],
    bins=[0, 12, 18, 40, 60, 100],
    labels=['child', 'teen', 'adult', 'middle', 'senior']
)

In [14]:
#STEP 4: HEALTH RISK SCORE
df_fe['health_risk'] = (
    df_fe['Hipertension'] +
    df_fe['Diabetes'] +
    df_fe['Alcoholism'] +
    df_fe['Handcap']
)

In [15]:
#STEP 5: SUPPORT NEED FEATURE
df_fe['needs_support'] = (
    df_fe['patient_needs_companion'] |
    df_fe['under_12_years_old'] |
    df_fe['over_60_years_old']
)

In [16]:
#STEP 6: WEATHER FEATURES
df_fe['high_rain'] = (df_fe['average_rain_day'] > df_fe['average_rain_day'].median()).astype(int)
df_fe['high_temp'] = (df_fe['max_temp_day'] > df_fe['max_temp_day'].median()).astype(int)

df_fe['weather_risk'] = df_fe['high_rain'] + df_fe['high_temp']

In [17]:
#STEP 7: INTERACTION FEATURES
df_fe['age_health_interaction'] = df_fe['age'] * df_fe['health_risk']

In [19]:
#STEP 8: SPECIALTY FEATURE
high_risk_specialties = [
    'psychotherapy',
    'speech therapy',
    'physiotherapy',
    'occupational therapy'
]

df_fe['specialty_risk'] = df_fe['specialty'].apply(
    lambda x: 1 if x in high_risk_specialties else 0
)

In [20]:
df_fe.shape

(109304, 39)

In [23]:
df.to_csv("../data/Feature_Engineering.csv")
print("data daved")

data daved

In [24]:
df_fe.shape

(109304, 39)